services:
  db:
    image: postgres:16-alpine
    container_name: testem-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-testem}
      POSTGRES_USER: ${DB_USER:-testem}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-testem}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testem-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME:-testem}
      DB_USER: ${DB_USER:-testem}
      DB_PASSWORD: ${DB_PASSWORD:-testem}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
